### ISSUE TITLE
Creating texture from byte[] array

### ISSUE THREAD

**Issue by wrymn** [ice1000/jimgui#11]
Hello,

could we have option to create texture id from byte array? Currently we can only load it from file.

Thank you

**Comment by ice1000** [comment]
It depends on the format of the byte array.. It's really hard since there're both dx9 and glfw implementations and I want to try my best to make all API cross-platform.

It's easy to implement a `JImTextureID.glfwFromBytes`, though. I'm on a train now, will do this about 1 hour later

**Comment by wrymn** [comment]
Thank you @ice1000 
The byte[] array would be encoded as .png

**Comment by ice1000** [comment]
I'll assume your byte array is the same format as the return value of `stbi_load`, and you have to provide width and height. Is that OK?

If not, maybe I should explore deeper into `stb_image`...

**Comment by ice1000** [comment]
@wrymn Could u plz give me a sample `byte[]` or some code that can produce the sample `byte[]`?

It's done and I want to test it.

**Comment by wrymn** [comment]
@ice1000 thank you.

Yes give me a sec, I need to create png from our internal screen capture method.

**Comment by wrymn** [comment]
The image is 2048x1024, it doesnt even want to print to console and I cannot reduce it. I will have to try it for myself :)
What is the version so gradle can upgrade it?

**Comment by ice1000** [comment]
The master branch. I'm quite confused that CircleCI cannot provide publicly available artifacts downloading.

**Comment by ice1000** [comment]
Let me see if I can upload the jar to bintray..

**Comment by ice1000** [comment]
@wrymn Please mention, the glfw backend is only available on Linux/MacOS... That makes testing hard, since I thought you're using Windows.

**Comment by ice1000** [comment]
@wrymn Done, `v0.4-1`

**Comment by ice1000** [comment]
I highly recommend you to create a smaller `byte[]` sample with the same format as the 2048x1024 one, if you failed to test it / you don't have Linux dev environment...

**Comment by wrymn** [comment]
Thank you for the upload.

The new method is there, but as you mentioned, imgui won`t start.
Our entire company is using windows. 
Cannot the method be converted/added the same way as rest of code was?

**Comment by ice1000** [comment]
If you're sure that your file format is exactly the same as a png file, I'll have a try anyway.

And DX9 implementation will be available later since currently I'm using some API that requires you to pass a file path.

**Comment by ice1000** [comment]
@wrymn Retry, plz. `v0.4-2`.

**Comment by ice1000** [comment]
The one for GLFW works.

**Comment by ice1000** [comment]
Refactored, no longer need `width` and `height` argument

**Comment by wrymn** [comment]
Thank you @ice1000 for the method.

We have some issues currently with our framework that it is not very compatible and the moment I run imgui it crashes on OpenGL access violation.
Until I resolve this, we are kinda stuck.

But if we resolve it, I will try the new method as soon as I can.

**Comment by ice1000** [comment]
@wrymn `v0.4-3`

**Comment by ice1000** [comment]
[jni-glfw-only.zip](https://github.com/ice1000/jimgui/files/2114294/jni-glfw-only.zip)

Created a CMake project that uses glfw only and doesn't detect OS.
You may load the `dll`s compiled from this project instead of using `JniLoader.load()`

**Comment by wrymn** [comment]
@ice1000 thank you I will try that.
But you have mentioned that it runs on DirectX on windows? Is it even compatible to run direct and opengl at the same time?

**Comment by ice1000** [comment]
Tested the GLFW backend on Linux, works like a charm.

**Comment by wrymn** [comment]
@ice1000 I need a confirmation, does jmgui runs on DirectX on windows?

**Comment by ice1000** [comment]
Yes, currently and defautly.

**Comment by ice1000** [comment]
You need OpenGL, this is why I created the cmake project that can build a dll using OpenGL on Windows for you. Maybe such dll will be merged into future versions, or become sub-projects.

**Comment by ice1000** [comment]
Now I have a Windows server! I can compile the glfw backend for windows myself now.

**Comment by wrymn** [comment]
We have not been able to create .dll from project you provided, it has too many dependencies and a lot of stuff breaks. Me and other programmer tried.

However I have a question, when does imgui swap its buffer? Do I have to run imgui only via
```
JImGuiUtil.runWithinPer(20000, 15, imGui -> {
})
```
?

We are on same thread as our framework. I need to understand in what order imgui renders and calls its methods, so I can synchronize it with our framework.

**Comment by wrymn** [comment]
Thank you @ice1000, it is now working, I can run both our game and editor window at the same time.
Will keep you posted!

**Comment by wrymn** [comment]
@ice1000 it seems when I try to render texture I created from bytes, application crashes.
Text renders normally.

Following is full crash dump log: https://pastebin.com/gZJctWcq

Any ideas?

**Comment by ice1000** [comment]
Superseded by #12
