### ISSUE TITLE
GLFW support for Windows

### ISSUE THREAD

**Issue by wrymn** [ice1000/jimgui#12]
I would like to request feature, where image would be rendered using only textureId, that was already created and rendered into by OpenGL.

Many existing imgui frameworks accept only textureId to draw images.

Thank you

**Comment by ice1000** [comment]
Do you mean `GLuint`?

**Comment by ice1000** [comment]
For testing purpose please try invoking this constructor

```java
        /**
         * package-private by design
         *
         * @param nativeObjectPtr native ImTextureID*
         *                        have different implementation on difference platforms
         * @param width           image width
         * @param height          image height
         */
        private JImTextureID(long nativeObjectPtr, int width, int height) {
                this.width = width;
                this.height = height;
                this.nativeObjectPtr = nativeObjectPtr;
        }
```

You can use reflection. If it works I'll add a public API for this.

**Comment by wrymn** [comment]
@ice1000 I have managed to create JImTextureID from its constructor, but when trying to draw it via gui.image(), it does crash. 
I am not sure why, maybe because that texture ID is used already by our framework?

I have tried to copy our texture into new generated texture, but result was the same, crash

```
int newTextureId = GL11.glGenTextures();
            GL43.glCopyImageSubData(GL_TEXTURE_2D, GLMain.backBufferTextureId, 0, 0, 0, 0, GL_TEXTURE_2D, newTextureId, 0, 0, 0, 0, 2048, 1024, 0);
```

**Comment by ice1000** [comment]
Windows? Oh dear, currently on windows you'll have to provide a `LPDIRECT3DTEXTURE9`.

Please wait I'll give you a glfw impl on Windows soon.

**Comment by wrymn** [comment]
It seems directx and opengl cannot share texture pointers (which is what I expected), so its back to trying it on opengl version of imgui (which we kinda failed to generate via cmake xD)

**Comment by wrymn** [comment]
Hi @ice1000, what is the progress on this issue?
Will we be able to use textureId from OpenGL on windows to display image?

**Comment by ice1000** [comment]
Fighting against windows glfw developing environment and https://youtrack.jetbrains.com/issue/KT-24946.
Will be available very soon.

**Comment by ice1000** [comment]
It's done! Waiting for the mac guy to give me the dylib.

**Comment by ice1000** [comment]
It's raising

    WGL: The driver does not appear to support OpenGL

While testing.
I don't know much about this, maybe it's just because the tester computer is not working properly?

**Comment by wrymn** [comment]
Every PC or mobile device has to support OpenGL, its how they draw on screen. Its bridge between application and GPU. 
So this is either old GPU driver or have to upgrade OpenGL version

**Comment by ice1000** [comment]
It says that `WGL_ARB_create_context_profile` is not defined..

**Comment by wrymn** [comment]
Try upgrading OpenGL: http://glew.sourceforge.net/

**Comment by ice1000** [comment]
Oh fuck. I give up, simply use the dll I'll upload about 1min later and use `System.load(absolute path to the dll)` instead of `JniLoader.load()`, and check if it works on your computer.

**Comment by ice1000** [comment]
Maybe it's just the problem of the testing computer.

**Comment by ice1000** [comment]
The dll is compatible with `v0.4-3`

**Comment by wrymn** [comment]
Thank you, so the DLL will use OpenGL and accept textureId?

**Comment by HoshinoTented** [comment]
Expected to be.

**Comment by HoshinoTented** [comment]
[jimgui-glfw.zip](https://github.com/ice1000/jimgui/files/2128836/jimgui-glfw.zip)

😃

**Comment by ice1000** [comment]
:arrow_up: My friend, owner of the Windows testing machine :smile:

**Comment by HoshinoTented** [comment]
The project files, works with mingw
[jimgui-glfw.zip](https://github.com/ice1000/jimgui/files/2128852/jimgui-glfw.zip)

**Comment by ice1000** [comment]
Thanks to @mikecovlee

**Comment by ice1000** [comment]
@wrymn Is that working for you? I'm gonna sleep since it's 3:19 a.m.

**Comment by wrymn** [comment]
@ice1000 both jimgui and our framework use GLFW, which is then initialized twice. 

Not sure how to solve this.

This error is thrown when either our framework inits GLFW first or jimgui inits GLFW first:

`ImGui Error 65544: Win32: Failed to register window class`

**Comment by ice1000** [comment]
Seems work (at least the creation of the window).

And the initialization of imgui and glfw is already separated in the newest version, which should work. The only reason I'm not publishing `v0.5` is that the mac guy is sleeping.

I'll create a `v0.4-4` without mac native library but with the newest progress, then delete `v0.4-3`.

**Comment by ice1000** [comment]
A new artifact is available: `org.ice1000.jimgui:extension:v0.4-4`, which brings you `JniLoaderEx.loadGlfw()`, which will use glfw on Windows.

**Comment by ice1000** [comment]
Done creating `v0.4-4`, plz try it out

**Comment by wrymn** [comment]
Will it fix the issue that GLFW is loaded twice? Not sure how GLFW initialization is working, but can it check if it is already initialized in system, or can I reuse it in order to prevent crash from duplicate initialization.

**Comment by ice1000** [comment]
@wrymn Yes, with `org.ice1000.jimgui.JImGui#fromExistingPointer(long, (optional) org.ice1000.jimgui.JImFontAtlas)`

**Comment by ice1000** [comment]
Use this factory function, I'll only initialize imgui but not glfw.

**Comment by wrymn** [comment]
In docs it says

```
a C++ pointer to {@code GLFWwindow} on Linux/OSX,
{@code NativeObject} (see dx9_impl.cpp) on Windows
```

Does it mean window context ID (created via glfwCreateWindow())? 
Or some glfw ID from its initialization?

**Comment by ice1000** [comment]
> Does it mean window context ID (created via glfwCreateWindow())?

Yes! Yes! Yes!

**Comment by wrymn** [comment]
I have used GLFW.glfwGetCurrentContext(), pointer ID seemed to be valid (675601680), but sadly I have been met with following error:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.ice1000.jimgui.JImVec4.allocateNativeObjects(FFFF)J
	at org.ice1000.jimgui.JImVec4.allocateNativeObjects(Native Method)
	at org.ice1000.jimgui.JImVec4.<init>(JImVec4.java:34)
	at org.ice1000.jimgui.JImGui.<init>(JImGui.java:52)
	at org.ice1000.jimgui.JImGui.fromExistingPointer(JImGui.java:75)
```

Just for clarification, now I only need to call JImGui.fromExistingPointer() before I can start to render right? Or is System.load() call still necessary?

**Comment by ice1000** [comment]
Ok, let me explain the whole correct process:

+ Add `org.ice1000.jimgui:extension:v0.4-4` to your dependencies
+ No more `System.load`
+ `JniLoaderEx.loadGlfw()`
+ `try (JImGui gui = JImGui.fromExistingPointer(your window pointer) { your old gui loop code here }`

**Comment by ice1000** [comment]
Complete example:

```java
import org.ice1000.jimgui.JImGui;
import org.ice1000.jimgui.JImTextureID;
import org.ice1000.jimgui.util.JniLoaderEx;

import java.lang.reflect.Constructor;

public class Main {
	public static void main(String[] args) throws NoSuchMethodException {
		JniLoaderEx.loadGlfw();
		try (JImGui gui = JImGui.fromExistingPointer(window pointer)) {
			Constructor<JImTextureID> constructor = JImTextureID.class.getConstructor(long.class, int.class, int.class);
			JImTextureID textureID = constructor.newInstance(texture id, width, height);
			while (!gui.windowShouldClose()) {
				gui.initNewFrame();
				gui.image(textureID);
				gui.render();
			}
		}
	}
}
```

**Comment by ice1000** [comment]
Sorry for the non-public constructor, there will be a public factory function in `v0.5`

**Comment by wrymn** [comment]
```
    private JImGui gui;

    @Override
    public void tick() {
		
		// Our framework initializes and creates new GLFW window before this method runs
        if(gui == null){
            Log.message("window poineter: " + GLFW.glfwGetCurrentContext() + " GLFW version: " + GLFW.glfwGetVersionString());
            JniLoaderEx.loadGlfw();
            gui = JImGui.fromExistingPointer(GLFW.glfwGetCurrentContext()); // Crash here
        }
	}
```

This is code I use. Both jimgui extension and core version are v.4-4

**Comment by ice1000** [comment]
Ahhh... I know! The C++ codes in the dll is not up-to-date.

Let me update it, and will give you a finally working one

**Comment by wrymn** [comment]
If this will all work I will buy you a car...
If you had any idea what consequences this will have if it will work :D

**Comment by wrymn** [comment]
@ice1000 any news regarding your last message?

**Comment by ice1000** [comment]
The Mac guy has uploaded the dylib. Last step: build the newest version. (Many files are affected)

**Comment by ice1000** [comment]
@wrymn Done! `v0.4-5` -- if it works, this version will become `v0.5`

**Comment by wrymn** [comment]
I have changed dependency for core and extension for `v0.4-5`, but sadly as soon as I call `initNewFrame()`, it does crash

Here is full crash log:
https://pastebin.com/6LRVWSJH

Code I use:
```
    private JImGui gui;

    @Override
    public void tick() {
        if(gui == null){
            long pointer = GLFW.glfwGetCurrentContext();
            Log.message("window pointer: " + pointer);
            JniLoaderEx.loadGlfw();
            gui = JImGui.fromExistingPointer(pointer);
            // Start to render on second frame
            return;
        }

        //Crash here
        gui.initNewFrame();
        gui.text("Test");
        gui.render();
    }
```

**Comment by wrymn** [comment]
I have tried running imgui on separate thread.
The imgui loads and does not crash. I can render our game as well as imgui window with text etc.

However, when I create new texture from pointer ID and try to render it, it crashes on gui.render() method.

Again, crash log: 
https://pastebin.com/hwRAsRpD

**Comment by ice1000** [comment]
I think I've figured out why is that happending..

**Comment by ice1000** [comment]
Tried fixing this in `v0.4-6`... Added `gl3wInit` in `fromExistingPointer`..

**Comment by wrymn** [comment]
The imgui no longer crashes when in main thread with our framework on **initNewFrame()**

But sadly, it still does crash when trying to render texture from pointer, same crash as before (https://pastebin.com/hwRAsRpD)

```
    private void startImgui() {
        JniLoader.load();
        JImGui gui = new JImGui();
        JImTextureID textureID = JImTextureID.fromExistingID(GLMain.backBufferTextureId, 2048, 1024);
        while (!gui.windowShouldClose()) {
            gui.initNewFrame();
            gui.image(textureID, 500, 500);
            gui.render();
        }
    }
```
Does it still use GLFW when not forcing it with **JniLoaderEx.startGlfw()**? Because it seems I cannot using when not giving it existing pointer

**Comment by ice1000** [comment]
Could you plz give me a minimum crashing project? It's too hard to do this "remote debug" and the JVM dump message does not actually help..

**Comment by ice1000** [comment]
> Does it still use GLFW when not forcing it with JniLoaderEx.startGlfw()?

No. Currently you can only use the glfw backend on Windows with `JniLoaderEx.loadGlfw()`

**Comment by ice1000** [comment]
What about this?

```java
    private void startImgui() {
        JniLoaderEx.loadGlfw();
        JImGui gui = new JImGui();
        JImTextureID textureID = JImTextureID.fromExistingID(GLMain.backBufferTextureId, 2048, 1024);
        while (!gui.windowShouldClose()) {
            gui.initNewFrame();
            gui.image(textureID, 500, 500);
            gui.render();
        }
    }
```

**Comment by wrymn** [comment]
I am sorry, I cannot give you project, because our framework belongs to client, and I cannot give your sources.

I think I know where the problem is.

**Option 1**
- I need to create window that was created by imgui OpenGL, while our application is running on GLFW as well
- now when I use `JImGui.fromExistingPointer()`, imgui will start to render into window of our application, it will not create it`s own window, which is incorrect

**Option 2**
- imgui and our framework will run on separate threads. This means GLFW can run for both of them 
- but when this happens, imgui runs on DirectX and will not accept OpenGL textureId
- I need to run imgui on GLFW via `JniLoaderEx.loadGlfw();` and then create `new JImGui()`

```
JniLoaderEx.loadGlfw();
JImGui gui = new JImGui(); // Crash here
```

it does crash:

```
Unknown error has happened during initialization!
ImGui Error 65544: Win32: Failed to register window class
```

So both Option 1 and Option 2 fails. Whichever can be fixed will fix the entire issue

**Comment by ice1000** [comment]
I'm interested in Option 1. Rendering in the window created by you is the expected behavior, if you need new window, simply `new JImGui`, or pass another window pointer to `fromExistingPointer`.

What are you trying to do by this?

**Comment by ice1000** [comment]
The error in Option 2 looks like glfw/glfw#469

**Comment by wrymn** [comment]
I need to run OpenGL for all options. As far as I understand, I can only achieve this on Windows via `JniLoaderEx.loadGlfw()`, right?

But when I load GLFW and create new window as you said, I get the error I already mentioned

```
JniLoaderEx.loadGlfw();
JImGui gui = new JImGui();
```
```
Unknown error has happened during initialization!
ImGui Error 65544: Win32: Failed to register window class
```

Or am I doing something wrong?

I need to render into imgui window and draw our game via texture into it, not the other way around.

**Comment by ice1000** [comment]
> I need to run OpenGL for all options. As far as I understand, I can only achieve this on Windows via `JniLoaderEx.loadGlfw()`, right?

100% correct

> Or am I doing something wrong?

Could you plz try replacing `new JImGui` with `JImGui.fromExistingPointer(create a new window pointer and put it here)`? I think this should work.

**Comment by wrymn** [comment]
This works

```
JniLoaderEx.loadGlfw();
long newPointer = GLFW.glfwCreateWindow(800, 500, "Test", 0, 0);
gui = JImGui.fromExistingPointer(newPointer);
```
but it somehow does not create new window, instead it will yet again render into window of our game framework.
Cannot imgui create new window?

**Sum up of what we need to achieve:**
- run our game framework, which initializes and renders via GLFW OpenGL, creates its window (this works)
- run imgui, which does not initialize GLFW OpenGL second time, but creates new window
- imgui will render into its own window and can use OpenGL textureId generated from our game framework

**Comment by ice1000** [comment]
What about using
```java
JniLoaderEx.loadGlfw();
long newPointer = GLFW.glfwCreateWindow(800, 500, "Test", 0, 0);
GLFW.glfwMakeContextCurrent(newPointer);
gui = JImGui.fromExistingPointer(newPointer);
```

**Comment by ice1000** [comment]
Superseded by #13

**Comment by wrymn** [comment]
Already tried that, it never creates new window, just renders into window of our framework.

btw why does `new JimGui()` not work and crashes into `ImGui Error 65544: Win32: Failed to register window class`?

**Comment by ice1000** [comment]
Let me figure it out tomorrow. 5:47 a.m. now..

**Comment by wrymn** [comment]
Ofc thank you.

Btw, you could simulate this issue when you create simple [GLFW ](https://github.com/badlogic/jglfw) application and create window ([guide](https://tutorialedge.net/java/lwjgl3/creating-game-window-lwjgl3-glfw/))
Then try to use jimgui on top of it.

Ofc testing would have to be on windows with jimgui-glfw version so it does use OpenGL

**Comment by ice1000** [comment]
Guess: place the call to `GLFW.glfwCreateWindow` on main thread should be a fix

**Comment by wrymn** [comment]
It was in the main thread on every instance
