### ISSUE TITLE
cannot find org_ice1000_jimgui_JImGui.h etc.

### ISSUE THREAD

**Issue by KnIfER** [ice1000/jimgui#15]
这些文件在哪里啊, kotlin 生成的吗?

错误(活动)	E1696	无法打开 源 文件 "org_ice1000_jimgui_JImGui.h"	jimgui32	e:\C\imgui\jimgui-master\core\jni\dx9_impl.cpp	7	
错误(活动)	E1696	无法打开 源 文件 "org_ice1000_jimgui_JImTextureID.h"	jimgui32	e:\C\imgui\jimgui-master\core\jni\dx9_impl.cpp	8	
错误	C1083	无法打开包括文件: “org_ice1000_jimgui_JImGui.h”: No such file or directory	jimgui32	e:\c\imgui\jimgui-master\core\jni\dx9_impl.cpp	7	
错误	C1083	无法打开包括文件: “org_ice1000_jimgui_JImVec4.h”: No such file or directory	jimgui32	e:\c\imgui\jimgui-master\core\jni\hand_written_bindings.h	9	
错误	C1083	无法打开包括文件: “org_ice1000_jimgui_NativeBool.h”: No such file or directory	jimgui32	e:\c\imgui\jimgui-master\core\jni\cpp_interop.cpp	7

**Comment by ice1000** [comment]
是 javac 生成的
