### ISSUE TITLE
v0.6

### ISSUE THREAD

**Issue by ice1000** [ice1000/jimgui#16]
@KnIfER

**Comment by ice1000** [comment]
@zxj5470 Mac dylib, upload a .zip in this issue

**Comment by KnIfER** [comment]
Actually I am implementing my own Java binding ..
with swig my method is easy and interesting, aside from some pointer issues.
![9](https://user-images.githubusercontent.com/11593903/42722394-cb442e78-877d-11e8-81b1-4b0a1e8bb60d.png)
```
		    static {
		    	 System.load("E:\\C\\swig\\libExample.so");
		    }

	        public static void main(String args[]){
	        	jimgui.initGLFWindow();
	        	
	        	ImGuiIO io = jimgui.GetIO();
	        	io.getFonts().AddFontFromFileTTF("E:\\assets\\fonts\\SourceHanSansCN-Regular.ttf", 18.0f);
	        	
	        	while(jimgui.glfwWindowShouldClose(jimgui.getWindow())==0) {
	        		jimgui.initNewFrame();
	        		jimgui.Begin("w1",null,ImGuiWindowFlags_.ImGuiWindowFlags_AlwaysAutoResize.swigValue());
	        		jimgui.Text(System.currentTimeMillis()+"asdasd");
	        		jimgui.End();
	        		jimgui.ShowFontSelector("哈哈哈");
	        		jimgui.render();
	        	}
	        	
	        	
	        }
```
I am using swig and mingw64+mysys .

**Comment by ice1000** [comment]
It's because you're using glfw implementation, not dx9..

**Comment by ice1000** [comment]
I'm waiting @zxj5470 to reply me

**Comment by ice1000** [comment]
I believe with v0.5 you're old code will work if you replace `JniLoader.load()` with `JniLoaderEx.loadGlfw()` in `extension` module

**Comment by KnIfER** [comment]
yes, you are right!  
using JniLoaderEx will solve the problem.

**Comment by ice1000** [comment]
@KnIfER I'm syncing the newest imgui, and it's almost done.

**Comment by ice1000** [comment]
Enjoy v0.6
