### ISSUE TITLE
ImGui implOpenGL3 default use glsl version 1.30, not supported on some macOS

### ISSUE THREAD

**Issue by Jason0214** [ice1000/jimgui#20]
```
ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to compile vertex shader!
ERROR: 0:1: '' :  version '130' is not supported
ERROR: 0:2: '' :  #version required and missing.

ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to compile fragment shader!
ERROR: 0:1: '' :  version '130' is not supported
ERROR: 0:2: '' :  #version required and missing.

ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to link shader program!
ERROR: One or more attached shaders not successfully compiled
```

it may related to https://github.com/ocornut/imgui/issues/1938 and https://github.com/ocornut/imgui/issues/1466

looks like there is way to tell imgui use specific glsl version, but no idea how to do it in java binding

**Comment by Jason0214** [comment]
it's weird, looking at the code here https://github.com/ice1000/jimgui/blob/f649b7764332dcc0ca8ad584f4afbec267db5207/core/jni/glfw_impl.cpp#L121,  it seems be properly handled,

**Comment by ice1000** [comment]
This is way too complicated for the purpose I created this library...

Maybe passing an extra argument to the jni library?

**Comment by Jason0214** [comment]
I will give it some try myself later to see if I can solve it.
