### ISSUE TITLE
NEED HELP WITH A JAVA PROGRAM, PLEASE! 

### ISSUE THREAD

**Issue by xashen7** [ice1000/jimgui#21]
Create the next Java program: given two lists (you must choose the data lists lines that are considered suitable for the solution of the project: ----Simple Linear Lists, Linear Circular Lists, Double Chained Linear Lists----) polynomial1 and polynomial2, which represent polynomials, elaborate the methods that return in a list sumapoli the sum of the polynomials (polynomial1 + polynomial2) and in a list of multiplication products of the polynomials (polynomial1 * polynomial2).
The list is stored in an object of the class "Polynomial" and each element of the list is an object of the class Term; at a general level, a Polynomial will be made up of a finite number of Terms.
The polynomials are read through a plain text of the name "Polin.txt", with the following format: 

**_Coefficient-1, exponent-1; Coefficient-2, exponent-2;_** 

The file must contain ONLY two lines, where each one represents polynomial, these can not be, SECURE, that the terms are not repeated. According to the following example:

**_2x ^ 2 + 3x + 2_**

It would be represented in the plain text file as:

**_2.2; 3.1; 2.0_**

The independent term "2" will have the exponent "0". FOR EFFECTS OF THE PROBLEM, SUPPOSE THAT THE VARIABLE IS ALWAYS "X".

An interface must be created to carry out the project, objects for the operation and tests of this.

**Comment by ice1000** [comment]
You need to pay me for doing a homework for you.
