### ISSUE TITLE
Migrate newest imgui to here

### ISSUE THREAD

**Issue by ice1000** [ice1000/jimgui#27]

**Comment by Mr00Anderson** [comment]
Are `Tabs` apart of this update? 
[Tabs - ImGui](https://github.com/ocornut/imgui/blob/cb7ba60d3f7d691c698c4a7499ed64757664d7b8/imgui.h#L576)

**Comment by ice1000** [comment]
I did not continue developing this because I don't have a Mac thus cannot build a dylib with it

**Comment by ice1000** [comment]
> Are Tabs apart of this update?
> Tabs - ImGui

It's supposed to be added easily

**Comment by Mr00Anderson** [comment]
Would procuring a cloud solution for the mac be useful? Microsoft offers free mac agents and its free for open source. I use the mac ones since I have yet to procure a Mac myself. I could add the tabs to the code base then. Not familiar with this project build scripts yet, so might take me some time to get to it.

**Comment by ice1000** [comment]
> Would procuring a cloud solution for the mac be useful? Microsoft offers free mac agents and its free for open source. I use the mac ones since I have yet to procure a Mac myself. I could add the tabs to the code base then. Not familiar with this project build scripts yet, so might take me some time to get it complete.

Could u help me? I've just tried to revive this project, bumping the dependent toolchains to the most (or second-most) recent versions, use the official imgui sources (instead of my own fork, which has some private additions but very old), and the build script works.

**Comment by ice1000** [comment]
To build, `./gradlew build` on mac and you can find a `libjimgui.dylib` file in the `res` directory.

Currently there are some trivial compilation errors due to API changes, working on fixing them

**Comment by Mr00Anderson** [comment]
https://dev.azure.com/mr00anderson/JImGui
For now working on setting up the build pipelines now. Well see what happens.

**Comment by Mr00Anderson** [comment]
Ill try to get this working tonight on my windows and then windows pipeline on devops azure. After that Ill work on mac and linux.

I wanna also propose elevating the demo into the main library from test eventually. Would be useful to allow people to open the demo and see whats possible, or even if we just JNI to the demo from `JimGui`. In my editor I am making I want to allow anyone to see the demo, to see capabilities.

**Comment by Mr00Anderson** [comment]
So you want to pull the files directly from the ImGui repo?

**Comment by ice1000** [comment]
> So you want to pull the files directly from the ImGui repo?

You don't need to do so, the build script will download the minimum required files for you.
Just run `./gradlew build` with:

+ CMake at least 3.12 (sorry for this. Because I need VS 16 2019 on Windows, which requires the most recent release)
+ `JAVA_HOME` configured properly

**Comment by Mr00Anderson** [comment]
I thought above you were asking to have me use the official sources. Ooooh I understand now. Yes I always use the source library first, most of the stuff in my editor I used from the c++ and just guessed where it was in JImGui.

**Comment by ice1000** [comment]
Because this project is not maintained for a while. Now it's revived

**Comment by ice1000** [comment]
Recent commits are building successfully, working on coaxing CIs and new APIs

**Comment by ice1000** [comment]
Tab APIs are added

**Comment by ice1000** [comment]
Can anyone build a mac dylib for me please

**Comment by Mr00Anderson** [comment]
I am working on it, trying to with DevOps Azure. Might be a day or two.

**Comment by Mr00Anderson** [comment]
I am stuck messing with the Build Agents Java for some reason doesn't come with JavaFX. So looking at how to change the demands so we can get the dynlib automatically.

**Comment by ice1000** [comment]
Tested on Windows and Linux

**Comment by Mr00Anderson** [comment]
There is some code that uses JavaFX
![image](https://user-images.githubusercontent.com/1356935/58739100-95bde180-83d6-11e9-99b7-dc33da549dc0.png)

**Comment by ice1000** [comment]
They're removed: 2d508e2dc38bec18a2b8bf68c2dca4d9d415a947

**Comment by ice1000** [comment]
Btw, now I required CMake 3.14 because of Visual Studio 2019 only. If you're building it with MacOS (thus no Visual Studio), you can manually edit the `CMakeLists.txt` to downgrade the dependent CMake version to 3.5 and use a lower version

**Comment by Mr00Anderson** [comment]
I got the pipeline working with the agent dependencies. Just having issues with some test? I am using the most recent commit.
```
Download https://pic4.zhimg.com/61984a25d44df15b857475e7f7b1c7e3_xl.jpg
> Task :core:downloadIce1000
> Task :core:processTestResources
> Task :core:testClasses

> Task :core:test FAILED
Resolved org.jetbrains:annotations:16.0.1 in :core:testRuntimeClasspath 
Resolved junit:junit:4.12 in :core:testRuntimeClasspath 
2019-06-01 00:06:20.878 java[1398:7846] WARNING: nextEventMatchingMask should only be called from the Main Thread! This will throw an exception in the future.
2019-06-01 00:06:20.878 java[1398:7846] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], /BuildRoot/Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1575.12/Foundation/Misc.subproj/NSUndoManager.m:361
2019-06-01 00:06:20.879 java[1398:7846] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], /BuildRoot/Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1575.12/Foundation/Misc.subproj/NSUndoManager.m:361
2019-06-01 00:06:20.883 java[1398:7846] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff35140e39 __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff5f88d3c6 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3515be3e +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fff37418c85 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   Foundation                          0x00007fff3734bcfa +[NSUndoManager(NSPrivate) _endTopLevelGroupings] + 473
	5   AppKit                              0x00007fff326fb915 -[NSApplication run] + 916
	6   libglfw.3.dylib                     0x0000000114753804 _glfwPlatformCreateWindow + 81
	7   libglfw.3.dylib                     0x000000011474e533 glfwCreateWindow + 460
	8   libjimgui.dylib                     0x0000000114a0ba6c Java_org_ice1000_jimgui_JImGui_allocateNativeObjects + 188
	9   ???                                 0x0000000114bde3a7 0x0 + 4642956199
	10  ???                                 0x0000000114bcdb10 0x0 + 4642888464
	11  ???                                 0x0000000114bcdffd 0x0 + 4642889725
	12  ???                                 0x0000000114bcdffd 0x0 + 4642889725
)
libc++abi.dylib: terminating with uncaught exception of type NSException

FAILURE: Build failed with an exception.
```

**Comment by ice1000** [comment]
> I got the pipeline working with the agent dependencies. Just having issues with some test? I am using the most recent commit.

Don't worry, it's because something mentioned in README (about a JVM argument).
Could you please upload `/core/res/native/libjimgui.dylib` to this thread?

**Comment by Mr00Anderson** [comment]
[Download URL](https://dev.azure.com/mr00anderson/_apis/resources/Containers/199336?itemPath=drop%2Fcore%2Fres%2Fnative%2Flibjimgui.dylib)


[libjimgui.zip](https://github.com/ice1000/jimgui/files/3243678/libjimgui.zip)

**Comment by ice1000** [comment]
Thanks

**Comment by ice1000** [comment]
Released 0.8 on bintray. Enjoy your tabs.

Tested on Ubuntu Linux 18.04, works like a charm.

**Comment by ice1000** [comment]
Tested tabs on Windows 10, works like a charm
![image](https://user-images.githubusercontent.com/16398479/58756192-24e6fa00-84a8-11e9-9b77-769af5380c7e.png)

**Comment by Mr00Anderson** [comment]
![image](https://user-images.githubusercontent.com/1356935/58767960-1872a800-8561-11e9-963a-33ea31a5d5cd.png)

**Comment by ice1000** [comment]
FYI u can use a `CheckBox` for `enabled` option.

**Comment by Mr00Anderson** [comment]
> FYI u can use a `CheckBox` for `enabled` option.

Yea I just have it locked as read only atm.

**Comment by ice1000** [comment]
@Mr00Anderson Might need your help again -- for #31

**Comment by ice1000** [comment]
Haven't worked on adding the missing functions here yet, but that's gonna be in close future

**Comment by ice1000** [comment]
s/close/near/
