### ISSUE TITLE
Libgdx

### ISSUE THREAD

**Issue by xpenatan** [ice1000/jimgui#28]
Hi, is it possible to use with libgdx?

Tried out kotlin version and there is a bad memory leak over there..

**Comment by ice1000** [comment]
I'm planning an update of this library, it's just a matter of time.

By update I mean sync the C++ codes with the newest official code.

(Probably I need to give up my own modified version and follow the official release).

**Comment by ice1000** [comment]
> Hi, is it possible to use with libgdx?

No.
