### ISSUE TITLE
Flags design

### ISSUE THREAD

**Issue by Mr00Anderson** [ice1000/jimgui#37]
I was thinking that all flags classes should be enumerations with a value field.  Are the flags manually or auto generated?

Reason: This would allow usage as an enum/class or an int.

Instead of 
```java
public interface JImSelectableFlags {
	int Nothing = 0;
	/** Clicking this don't close parent popup window */
	int DontClosePopups = 1;
	/** Selectable frame can span all columns (text will still fit in current column) */
	int SpanAllColumns = 1 << 1;
	/** Generate press events on double clicks too */
	int AllowDoubleClick = 1 << 2;
}
```
it would be
```java
 public enum SelectableFlags {
        Nothing(0),
        /** Clicking this don't close parent popup window */
        DontClosePopups(1),
        /** Selectable frame can span all columns (text will still fit in current column) */
        SpanAllColumns(1 << 1),
        /** Generate press events on double clicks too */
        AllowDoubleClick(1 << 2);

        public int value;

        SelectableFlags(int value) {
            this.value = value;
        }
    }
```

**Comment by ice1000** [comment]
They're manually written

**Comment by Mr00Anderson** [comment]
You can assign me.

**Comment by Mr00Anderson** [comment]
Actually maybe this isnt such a good idea?

**Comment by Mr00Anderson** [comment]
It may be better for me to write a wrapper around it to reverse look up to a friendly name, then make these kinds of changes. Plus doing so would make it less like native ImGui.

**Comment by ice1000** [comment]
> Actually maybe this isnt such a good idea? It may be better for me to write a wrapper around it to reverse look up to a friendly name, then make these kinds of changes. Plus doing so would make it less like native ImGui.

Contributions are welcomed. I'm just a bit tired of writing another code generator 😭

**Comment by Mr00Anderson** [comment]
I changed half of it last night. But this will cause everyone to have to use flag.value and all existing would break for those using the library. I will think about this more about a enum to match the data, but have a reverse look up to return string friendly flag names. No need for auto gen code.

**Comment by Mr00Anderson** [comment]
Sample of what I will be adding, if everyone is good with it. 

```package org.ice1000.jimgui.flag;

/**
 * @author ice1000
 * @since v0.1
 */
public interface JImBackendFlags {
	int Nothing = 0;
	/** Back-end supports and has a connected gamepad. */
	int HasGamepad = 1;
	/** Back-end supports reading GetMouseCursor() to change the OS cursor shape. */
	int HasMouseCursors = 1 << 1;
	/**
	 * Back-end supports io.WantSetMousePos requests to reposition the OS mouse position
	 * (only used if {@link JImConfigFlags#NavEnableSetMousePos} is set).
	 */
	int HasSetMousePos = 1 << 2;

// ADDITIONS --------------------------------
	enum Type implements Flag {
		/**
		 * Used for reverse lookup results and enum comparison. 0 Used to prevent ImGui errors from 
		 * unexpected results
		 */
		NoSuchFlag(0),
		/** @see JImBackendFlags#Nothing */
		Nothing(0),
		/** @see JImBackendFlags#HasGamepad */
		HasGamepad(1),
		/** @see JImBackendFlags#HasMouseCursors */
		HasMouseCursors(1 << 1),
		/** @see JImBackendFlags#HasSetMousePos */
		HasSetMousePos(1 << 2);

		public final int flag;

		Type(int flag) {
			this.flag = flag;
		}

		@Override
		public int get() {
			return flag;
		}
	}

	static Type reverseLookup(int flag){
		Type[] values = Type.values();
		for (int i = 0; i < values.length; i++) {
			Type value = values[i];
			if(value.flag == flag) return value;
		}
		return Type.Nothing;
	}
}
```

**Comment by ice1000** [comment]
How about `HasGamepad(JImBackendFlags.HasGamepad)` instead if `HasGamepad(1)`?

**Comment by ice1000** [comment]
@Mr00Anderson For markdown syntax, you should probably learn how to add syntax highlight to your code blocks to make them readable -- https://help.github.com/en/articles/creating-and-highlighting-code-blocks#syntax-highlighting

**Comment by Mr00Anderson** [comment]
@ice1000 sounds good for the above. The syntax highlighting was an oversite. I always forget to add the syntax type.

**Comment by ice1000** [comment]
Ok
