### ISSUE TITLE
Is it possible to add imgui to lwjgl?

### ISSUE THREAD

**Issue by ejamshidiasl** [ice1000/jimgui#44]
Hello
i used it in java applciation and it is really good
thanks

is it possible to add it to lwjgl glfw window?

**Comment by ice1000** [comment]
As you can see many people have paid their souls trying to achieve this but failed:
#12 #13 #18 #19 #28

**Comment by ice1000** [comment]
Contribution is welcomed

**Comment by ejamshidiasl** [comment]
i can run 2 windows side by side
but i want to run imgui window inside lwjgl
i am working on it now....

**Comment by ice1000** [comment]
> i can run 2 windows side by side

wut? wut os/jre r u using?

**Comment by ice1000** [comment]
Theoretically, exposing `ImGui::CreateContext` should make this possible, but I haven't tried

**Comment by ice1000** [comment]
Btw,

> i used it in java applciation and it is really good

what is applciation?

**Comment by ejamshidiasl** [comment]
import org.ice1000.jimgui.JImGui;
import org.ice1000.jimgui.util.JniLoader;
import org.lwjgl.glfw.GLFW;

public class Main {

    public Main(){
        GLFW.glfwInit();
        long window = GLFW.glfwCreateWindow(400,400,"window1",0,0);
        GLFW.glfwMakeContextCurrent(window);
        GLFW.glfwSwapInterval(1);

        GLFW.glfwShowWindow(window);


        JniLoader.load();
        try (JImGui imGui = new JImGui()) {
            // load fonts, global initializations, etc.
            imGui.initBeforeMainLoop();
            while (!imGui.windowShouldClose()) {
                // some drawing-irrelated initializations
                // mostly do nothing here
                imGui.initNewFrame();
                // draw your widgets here, like this
                imGui.text("Hello, World!");
                imGui.render();
            }
        }


        while (GLFW.glfwWindowShouldClose(window) == false){
            GLFW.glfwPollEvents();



        }

        GLFW.glfwTerminate();
    }

    public static void main(String[] args){
        new Main();
    }
}

**Comment by ice1000** [comment]
@ejamshidiasl you really should learn how to post codeblocks on github: https://help.github.com/en/articles/creating-and-highlighting-code-blocks

**Comment by ejamshidiasl** [comment]
thanks (for code blocks)

what is applciation? ---> application

**Comment by ice1000** [comment]
Try `JImGui.fromExistingPointer`

**Comment by ejamshidiasl** [comment]
OS: win 10
IDE: intellij idea
lwjgl: latest release

**Comment by ejamshidiasl** [comment]
i found something
in JImGui imGui = new JImGui() there is an argumant that gets anotherWindow handle
i am trying this now

**Comment by ice1000** [comment]
wut

**Comment by ice1000** [comment]
> Try `JImGui.fromExistingPointer`

@ejamshidiasl

**Comment by ejamshidiasl** [comment]
where to use it?

**Comment by ejamshidiasl** [comment]
wha is **nativeObjectPtr**?

**Comment by ejamshidiasl** [comment]
i find something cool
i think problem is in imGui.initBeforeMainLoop() function
because it loads other window handle

**Comment by ejamshidiasl** [comment]
may i ask you to change constructor?
line 222 file JImGui.java 
please add input argument (long window)

**Comment by ice1000** [comment]
I was just wrapping the native API of glfw, I have no idea how they work

**Comment by ice1000** [comment]
You can use reflection to access the `private initBeforeMainLoop(long)` function, and prove it works, and then I can make the function public.

**Comment by ejamshidiasl** [comment]
Hello
i downloaded new version on jimgui and now i can render it to lwjgl window
but there is a problem. imgui draws on top of lwjgl so i cannot see any opengl.
maybe problem is in initNewFrame

**Comment by ice1000** [comment]
I have no idea, you can dig imgui itself if you'd like to

**Comment by zeroeightysix** [comment]
> Hello
> i downloaded new version on jimgui and now i can render it to lwjgl window
> but there is a problem. imgui draws on top of lwjgl so i cannot see any opengl.
> maybe problem is in initNewFrame

Could you post the code for / make a new repository to show how you achieved this?

**Comment by hnOsmium0001** [comment]
It occured to me that JImGui is trying to use DirectX on Windows which makes it incompatible with LWJGL. However I'm not 100% sure of this guess: is it true?
If ture, how can I manually choose to use the glfw+opengl3 version?

**Comment by ice1000** [comment]
I don't know. There used to be a glfw+ogl3 native library, but I can't recall how to use it.

**Comment by Berksen** [comment]
Any update for this issue? im using libgdx for a project and libgdx itself spawns a window, while imgui spawns another.
My goal was to render imgui inside the libgdx existing window.
I can have access to the libgdx windowhandle but passing it as argument to JImGui constructor doesnt seem to change anything.
Maybe im doing something wrong?

**Comment by Berksen** [comment]
Using JImGui.fromExistingPointer(windowHandle) makes the program crash and a dump is returned.
Using gui=new JImGui(width,height,atlas,title,windowHandle) doesnt change anything, 2 windows appears anyway.

**Comment by videogreg93** [comment]
Why was this issue closed? I'm still not able to get this working in LibGDX.

**Comment by ice1000** [comment]
> Why was this issue closed? I'm still not able to get this working in LibGDX.

Me neither
