### ISSUE TITLE
Unicode character support

### ISSUE THREAD

**Issue by DVD8084** [ice1000/jimgui#47]
When using Unicode characters (such as Cyrillic letters) in JImGui widgets, they are displayed in native encoding.
For example, on Windows 10 (with Russian locale), after adding Cyrillic font ranges to font atlas, calling `text("Шахматы")` displays `РЁР°С…РјР°С‚С‹` (UTF-8 representation of "Шахматы" incorrectly read as a CP1251 string).
I'm assuming that the string's encoding is by default interpreted as a Unicode in the Java bindings, but as the system default encoding in ImGui's C++ implementation.

**Comment by ice1000** [comment]
Chinese characters used to work for me. Can you reproduce this in pure C++?

**Comment by DVD8084** [comment]
I cannot, even though I was sure it happened to me before when I was working with C++ ImGui. 
I can send you a reproducible Java example if needed.

**Comment by DVD8084** [comment]
[example.zip](https://github.com/ice1000/jimgui/files/3906398/example.zip)

**Comment by ice1000** [comment]
Do you understand how the `u8"bla"` things work in C++? How does it convert your string into utf8 sequences? Is your Java source code UTF-8-encoded?

**Comment by DVD8084** [comment]
1. Yes. I expected the string not to display properly without the `u8` literal, but it worked as normal both with the literal and without it.
2. The string is a default Java string literal. I haven't used any additional consersions, including custom string to bytes conversions.
3. Yes. Both Notepad++ and HxD confirm that.
See attached screenshot for an example of how it is displayed.
The original string (included in the demo) was "Съешь же ещё этих мягких французских булок, да выпей чаю."
![demo](https://user-images.githubusercontent.com/24571282/69890858-ed46f680-1300-11ea-84e7-2d938fbc2cf8.png)

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/69891757-f1f1b780-12cc-11ea-9890-15191c74d04a.png)

Is this what you've expected?

**Comment by DVD8084** [comment]
Yes, that is exactly what I expected.

**Comment by ice1000** [comment]
> Yes. Both Notepad++ and HxD confirm that.

You should **compile** your Java source as UTF-8, in addition to ensuring your Java source **is** UTF-8 encoded. Here's how:

```gradle
compileJava.options.encoding = 'UTF-8'
```

**Comment by ice1000** [comment]
If you're willing to help document this, please pull request me! So other people like you can save time.

**Comment by DVD8084** [comment]
Alright, thanks! Should I add a note to `README.md`, or document it inside `JImFont.java`/`JImFontAtlas.java`?

**Comment by ice1000** [comment]
Probably `README`

**Comment by DVD8084** [comment]
Done.

**Comment by seb321** [comment]
Hi,

I'm having a problem with selecting glyphs to load — the procedure takes glyph ranges, but no range provided by `getGlyphRangesFor*()` is suitable for me and I do not see a way to create them through the API. Is it possible?

**Comment by ice1000** [comment]
> Hi,
> 
> I'm having a problem with selecting glyphs to load — the procedure takes glyph ranges, but no range provided by `getGlyphRangesFor*()` is suitable for me and I do not see a way to create them through the API. Is it possible?

It is, but I haven't yet adapted the API for custom ranges. It's hard in general -- imagine you passes a two-dim array from Java to C++. There are some design choices to be made.

**Comment by ice1000** [comment]
Btw, I suggest opening new issue. @seb321
