### ISSUE TITLE
Release v0.10

### ISSUE THREAD

**Issue by ice1000** [ice1000/jimgui#49]
I have updated some methods & bindings. There should be a newer version.

**Comment by ice1000** [comment]
@zxj5470 Can you help me build a macos native dylib?

**Comment by ice1000** [comment]
Yay! Both CIs are fixed!

**Comment by aeris170** [comment]
When can we expect v0.10 to be uploaded to bintray? After #56, I need it in bintray(or any other repo) so I can use it :)

**Comment by ice1000** [comment]
> When can we expect v0.10 to be uploaded to bintray? After #56, I need it in bintray(or any other repo) so I can use it :)

I need a mac to build the macos native library :)

**Comment by aeris170** [comment]
I have a friend who has one but we are far away. Maybe I can get him to compile. No promises tho :)

**Comment by ice1000** [comment]
I'll me see what I can do for this too

**Comment by ice1000** [comment]
> When can we expect v0.10 to be uploaded to bintray? After #56, I need it in bintray(or any other repo) so I can use it :)

@aeris170 it's uploaded but still has some potential improvements. Will update later
