### ISSUE TITLE
sliderInt() and sliderFloat() don't work properly

### ISSUE THREAD

**Issue by DVD8084** [ice1000/jimgui#52]
When drawing a `sliderInt()`, the slider is drawn according to the value of `NativeInt`, but displays 0.000 instead.
When the slider is clicked, the value of `NativeInt` immediately changes to 0.
The same behavior was noticed with `sliderFloat()` and potentially other sliders.
Minimal reproducible example attached. (I used the glfw implementation, but I've had the same results on the directX implementation.)
[Main.txt](https://github.com/ice1000/jimgui/files/4142807/Main.txt)

**Comment by ice1000** [comment]
Can you reproduce this with the latest C++ implementation?

**Comment by DVD8084** [comment]
I couldn't reproduce it with the C++ implementation of dear imgui. The demo window function from the bindings (which calls the demo window from the C++ library) doesn't show such behavior either.

**Comment by ice1000** [comment]
It sounds somehow like a 32/64 bit issue? Should check out the implementation of `NativeInt`.

**Comment by DVD8084** [comment]
Alright. I'm running Windows 10 64-bit and used JDK 8 64-bit, if that helps.
Also, I checked it with `dragInt()` and `inputInt()` and they seem work as intended.

**Comment by ice1000** [comment]
This is weird. I can reproduce it :/

**Comment by ice1000** [comment]
Fixed on master
