### ISSUE TITLE
ImGui::SetCursorPosY, ImGui::SetCursorPosX missing?

### ISSUE THREAD

**Issue by newk5** [ice1000/jimgui#58]
I can't seem to find these functions inside the JImGui instance, are they missing?

**Comment by ice1000** [comment]
I don't think so

**Comment by ice1000** [comment]
No helpful information provided like versions and stuffs, closing

**Comment by newk5** [comment]
I can see the functions here: https://github.com/ocornut/imgui/blob/eb7849b477ff96d8d0cc9f2f4a304b5fc0f3ac1a/imgui.h#L350
But I cant see it inside the JImGui instance

**Comment by newk5** [comment]
I'm using 0.9 version, I'm on windows 10 64bit

**Comment by newk5** [comment]
I notice they seem to be in the source kotlin files here : https://github.com/ice1000/jimgui/blob/159087e3d55386d794e66498d173d5d6efe578fe/buildSrc/src/GenGenTask.kt#L86

But I can't access them from the JImGui instance, am I doing something wrong? @ice1000

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/99063557-a3bded00-25df-11eb-965a-bf9d345e2188.png)
I guess you can. They are made static

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/99063607-b0dadc00-25df-11eb-937b-801f3bbde558.png)
You can do it, it's just absent from the completion menu.

If you type `setCur` and hit Ctrl+Space, it'll show up:
![Uploading image.png…]()

**Comment by newk5** [comment]
ohh they're static, sorry I did not notice. Thank you for your help!

**Comment by ice1000** [comment]
I'm sorry for making 'em static :(

**Comment by newk5** [comment]
It's ok, that works too 😃
