### ISSUE TITLE
No matching field found: end for class org.ice1000.jimgui.JImGui

### ISSUE THREAD

**Issue by Tyruiop** [ice1000/jimgui#77]
Hi,

I'm interested in writing Clojure bindings on top of `jimgui`, however if I try to call `.end` on a `JImGui` I get the following error: 
`No matching field found: end for class org.ice1000.jimgui.JImGui`

Any idea how to fix that by any chance?

Thanks for the good work!

**Comment by ice1000** [comment]
It's a static member function from a superclass of JImGui. You can easily find it by writing the code in Java and use an IDE to find its definition.

**Comment by ice1000** [comment]
Closing as answered
