### ISSUE TITLE
Fonts don't seem to do ...anything.

### ISSUE THREAD

**Issue by LowSpecCorgi** [ice1000/jimgui#79]
So, I have a directory structure like so:
```brainfuck
src
 - main
  - java
    - ...
  - resources
    - fonts
      - Roboto-Bold.ttf
      - Roboto-Regular.ttf
  ```

Loading both fonts seem successful, by merit of no exception and such:
```java
largeFont = imGui.getIO().getFonts().addFontFromFile(getClass().getClassLoader().getResource("fonts/Roboto-Bold.ttf").getPath(), 48);
smallFont = imGui.getIO().getFonts().addFontFromFile(getClass().getClassLoader().getResource("fonts/Roboto-Regular.ttf").getPath(), 24);
```

But, when pushing the font like so:
```java
imGui.pushFont(largeFont);

imGui.text(
    WINDOW_TITLE
);

JImGuiGen.popFont();
```
Nothing happens.
The text is rendered, but with the default ImGui font, I'm not particularly sure why this is happening.

Help would be appreciated :)

**Comment by ice1000** [comment]
Try using absolute paths instead?

**Comment by LowSpecCorgi** [comment]
> Try using absolute paths instead?
```java
getClass().getClassLoader().getResource("fonts/Roboto-Regular.ttf").getPath()
```

Does return an absolute path to the resource

**Comment by LowSpecCorgi** [comment]
Oh wait you were right

I'm stupid

thanks for help

**Comment by ice1000** [comment]
> > Try using absolute paths instead?
> ```java
> getClass().getClassLoader().getResource("fonts/Roboto-Regular.ttf").getPath()
> ```
> 
> Does return an absolute path to the resource

I think that's a Java specific format of path. You need to give imgui (yes, imgui, not jimgui) a path that is recognizable by the C++ file IO library.

**Comment by ice1000** [comment]
You're not stupid, you're cute!
