### ISSUE TITLE
jimgui does not work after upgrade from 0.21.0 to 0.22.0 on linux

### ISSUE THREAD

**Issue by truemaker** [ice1000/jimgui#84]
I got this error when running my program

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007feb11acf0f4, pid=140089, tid=0x00007feb5527f700
#
# JRE version: OpenJDK Runtime Environment (8.0_312-b07) (build 1.8.0_312-8u312-b07-0ubuntu1~20.04-b07)
# Java VM: OpenJDK 64-Bit Server VM (25.312-b07 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libjimgui.so+0x580f4]  ImGui::PopStyleVar(int)+0x74
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/tre/gameengine/ThorbenEngine/hs_err_pid140089.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by ice1000** [comment]
.. and what is your glibc version? Maybe it's different from the one circleci uses.

**Comment by ice1000** [comment]
Closed as no response
