### ISSUE TITLE
停更了？

### ISSUE THREAD

**Issue by qqke** [ice1000/jimgui#86]
很不错的一个封装，为啥停更了？

**Comment by ice1000** [comment]
你需要哪些新版本的功能?

我已经换电脑, 新电脑不想安装 visual studio build tools, 所以短期应该没机会再 build.

**Comment by ice1000** [comment]
每次发版本特别麻烦, 需要收集数个 native 的 dll/so/dylib, 现在感觉维护的收益远小于付出量 (还得随上游更新改 API). 最新版本够我用十万年.

**Comment by qqke** [comment]
哈哈 票关的真快 有些API没转过来 比方说Table中 用ImGuiListClipper应该性能高些吧

**Comment by ice1000** [comment]
> 用ImGuiListClipper应该性能高些吧

我看看这个类型

**Comment by ice1000** [comment]
> 票关的真快

我回的也很快, 有具体问题开 issue 我会记录, 你问的问题我已经回答了就关了

**Comment by ice1000** [comment]
我记得是我停更的时候的最近几个版本弄了键盘事件的重构, 我没整明白那几个 API, 就停留在了搞这些重构前的状态. 你有兴趣帮忙迁移的话我会 review & merge 的.
