### ISSUE TITLE
Unsupported OS

### ISSUE THREAD

**Issue by MagM1go** [ice1000/jimgui#87]
java.lang.UnsupportedOperationException: Unknown OS Windows 11, please submit issue to https://github.com/ice1000/jimgui/issues

okay

**Comment by ice1000** [comment]
> java.lang.UnsupportedOperationException: Unknown OS Windows 11, please submit issue to https://github.com/ice1000/jimgui/issues
> 
> okay

😱

**Comment by MagM1go** [comment]
> > java.lang.UnsupportedOperationException: Unknown OS Windows 11, please submit issue to https://github.com/ice1000/jimgui/issues
> > okay
> 
> 😱

😱

**Comment by ice1000** [comment]
By the way I somewhat believe that this library should be rewritten in the way of https://github.com/ice1000/gdx-box2d. Maybe we can hopefully support #13

**Comment by ice1000** [comment]
Try `JniLoader.loadLib("jimgui-dx11.dll")`. Maybe it resolves your issue.

**Comment by ice1000** [comment]
Use that to replace `JniLoader.load()`.

**Comment by MagM1go** [comment]
ye that works
