### ISSUE TITLE
Drawing an image

### ISSUE THREAD

**Issue by wrymn** [ice1000/jimgui#9]
I am trying to draw an image.
The only parameter I can pass is an **JImTextureID**.

- the only way I can create this ID is via JImTextureID.fromFile()
- I provide name of texture .png file, it does not load

```
JniLoader.load();
URL resource =  this.getClass().getResource("img.png");
JImTextureID texture = JImTextureID.fromFile(resource);
```

This is my code, **resource** is loaded correctly.

Would you point me to a problem?

Error:

```
Exception in thread "main" java.lang.IllegalStateException: cannot load /D:/Development/Projects/Java/GradleEditor/out/production/resources/img.png
	at org.ice1000.jimgui.JImTextureID.fromFile(JImTextureID.java:41)
	at org.ice1000.jimgui.JImTextureID.fromFile(JImTextureID.java:53)
	at Application.init(Application.java:32)
	at Application.run(Application.java:23)
	at Application.main(Application.java:14)
```

**Comment by ice1000** [comment]
Could you please try replacing `JImTextureID.fromFile(resource)` with ``?

This doesn't happen on Linux. Maybe I should re-impl the API.

**Comment by ice1000** [comment]
You can see the path is converted to `/D:/Development/Projects/Java/GradleEditor/out/production/resources/img.png`, and the leading `/` is unexpected.

**Comment by wrymn** [comment]
@ice1000 thank you very much for the reply 

Sadly, still the same problem

code is now

```
        URL resource =  this.getClass().getResource("img.png");
        String path = resource.getPath().substring(1);
        System.err.println(path);
        JImTextureID texture = JImTextureID.fromFile(path);
```


but the issue persists

```
D:/Development/Projects/Java/GradleEditor/out/production/resources/img.png
Exception in thread "main" java.lang.IllegalStateException: cannot load D:/Development/Projects/Java/GradleEditor/out/production/resources/img.png
	at org.ice1000.jimgui.JImTextureID.fromFile(JImTextureID.java:41)
	at Application.init(Application.java:29)
	at Application.run(Application.java:22)
	at Application.main(Application.java:14)
```

**Comment by ice1000** [comment]
That should be a bug, or your image cannot be loaded by DirectX.

Could you plz upload your image here? You can just drag-and-drop the image to the comment and wait for a while.

**Comment by ice1000** [comment]
Could you please try loading this image?

https://avatars2.githubusercontent.com/u/16398479

**Comment by wrymn** [comment]
![img](https://user-images.githubusercontent.com/12801017/41501584-b2f33c06-71a7-11e8-923d-55e703ad1593.png)

that was the test image.
Your image did not load either.

Here is full java code, just to be safe:
https://pastebin.com/e6zD5amk

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/41501594-2f7581a8-71da-11e8-8f1b-093fe25e40e7.png)

Tested on my friend's laptop, it works..

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/41501629-c464e952-71da-11e8-8ae1-b79de05628df.png)


Your image...

Which operating system are you using? Do you have DirectX9 installed?

**Comment by wrymn** [comment]
@ice1000 now I see the issue. I have not created **new JImGui()** instance.

There should be some tutorial snippet code in github main page.

This is finally working

```
JniLoader.load();
        JImGui gui = new JImGui();
        URL resource =  this.getClass().getResource("/img.png");
        String path = resource.getPath().substring(1);
        System.err.println(path);
        JImTextureID texture = JImTextureID.fromFile(path);

        while(!gui.windowShouldClose()){
            gui.initNewFrame();
            gui.text("Hello JImGui");
            gui.image(texture, 100, 100);
            gui.render();
        }
```

**Comment by ice1000** [comment]
I see. It's due to a design problem of the API.

You should create the texture after the `JImGui` instance is created.

Try this code, I promise this will work! (flag

```java
public class Main {
    @SuppressWarnings("AccessStaticViaInstance")
    public static void main(String[] args) throws URISyntaxException {
        JniLoader.load();
        try (JImGui gui = new JImGui()) {
            JImTextureID imTextureID = JImTextureID
                    .fromFile(Paths.get(Main.class.getResource([path to your image]).toURI()));
            while (!gui.windowShouldClose()) {
                gui.initNewFrame();
                gui.image(imTextureID, imTextureID.width, imTextureID.height);
                gui.render();
            }
        }
    }
}
```

**Comment by ice1000** [comment]
My API is badly designed -- I've put the rendering framework (dx9 on win and ogl on \*nix) initialization code inside the constructor of `JImGui`, while the creation of the textures should be done after the initialization of the rendering framework.

My initial goal is to prevent the user from worrying about the rendering framework, this is why I've mixed the initialization together. AFAIK a small tutorial should be written, the API is somewhat misleading.

**Comment by wrymn** [comment]
@ice1000 now that this is finally working, I can ask the main question :D

In what state **jimgui** currently is? 
We are planning to create game editor on top of our existing java game SDK. Since I am the project lead, I was looking into best ways to create architecture for such a system.

I really like your port, its ease of use, texture loading etc.

Do you think in your opinion be this port capable of handling full game editor on top of existing framework?

**Comment by ice1000** [comment]
A new idea: make `createFromFile` a method of `JImGui`!

**Comment by ice1000** [comment]
@wrymn Create a new issue first, this issue should be closed.

**Comment by ice1000** [comment]
@wrymn Short answer: it's production ready if you just want to use the imgui api only.

To interact with the low-level API of the rendering framework, you need some hacking, but let's first move to another issue.
